# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7de81d6662441afca84d052dfe622e150b2bb9649b4ad46de1059755521993197b692b18ab71302680a695315cd36de861907e30ead32c5d9ccd363dcbd3b2b2

test:
  secret_key_base: 27cdfccdca6c69c41ce469e00e3a67eef836c76efafa62bdf9e832d277eda75c4b77d7f370e37aca5df6ac00437d9f0e45660181c04e46919d9f385461706e92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
